#!/usr/bin/env python3
"""Generate a docker-compose override from a resolved ConfigFlux snapshot.

>>> THIS IS USER-SIDE GLUE, NOT A PRODUCT FEATURE. <<<

ConfigFlux emits the resolved snapshot — the rich artifact that carries *every*
parameter and its full metadata across all lifecycle classes. It deliberately
does NOT emit docker-compose overrides, env-files, or any orchestrator-specific
shape (ADR-0032 D3/D5; docs/service-integration-guide.md, "Materializing an
env-file or compose override (user-side)"). Shaping the snapshot into whatever
your orchestrator consumes is a thin transform that lives in YOUR repository.

This script is exactly that transform, shown in the place a user would keep it:
alongside the service it configures. It walks resolved_output and writes the
resolved leaf values under one service's `environment:` block as sorted
COMPONENT_PARAM=value entries (uppercased keys). If your orchestrator wants an
env-file, a Helm values file, or a Kubernetes ConfigMap instead, you change THIS
file — the product surface does not move.

Lineage first: like any Pattern 1 consumer we verify resolve status is ok and
echo model_hash / resolve_hash into the override as comments, so the generated
fragment is traceable to the exact resolution it came from.

Usage:
  gen_compose_override.py --snapshot <resolve_result.json> --service <name> \
      [--out <compose.override.yml>]

Output goes to --out, or stdout if --out is omitted.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any


def scope_root(snapshot: dict[str, Any]) -> str:
    scope = snapshot.get("scope", "")
    return scope.split(":", 1)[1] if ":" in scope else scope


def env_pairs(snapshot: dict[str, Any]) -> list[tuple[str, Any]]:
    """Return sorted (COMPONENT_PARAM, value) pairs from resolved_output."""
    root = scope_root(snapshot)
    components = snapshot["resolved_output"][root]["components"]
    pairs: list[tuple[str, Any]] = []
    for component, cdef in components.items():
        for param, leaf in cdef.get("params", {}).items():
            key = f"{component}_{param}".upper()
            pairs.append((key, leaf.get("value")))
    return sorted(pairs)


def yaml_scalar(value: Any) -> str:
    """Render a JSON scalar as a double-quoted compose env value.

    Compose treats environment values as strings; quoting keeps an integer like
    200 or a URL with ':' unambiguous and avoids YAML type coercion surprises.
    """
    text = "true" if value is True else "false" if value is False else str(value)
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_override(snapshot: dict[str, Any], service: str) -> str:
    pairs = env_pairs(snapshot)
    lines = [
        "# GENERATED by gen_compose_override.py — DO NOT EDIT BY HAND.",
        "# This is a user-side transform of a ConfigFlux resolved snapshot, not a",
        "# product output (ADR-0032 D3). Regenerate it from the snapshot instead.",
        f"# scope        : {snapshot.get('scope')}",
        f"# model_hash   : {snapshot.get('model_hash')}",
        f"# resolve_hash : {snapshot.get('resolve_hash')}",
        'services:',
        f"  {service}:",
        "    environment:",
    ]
    for key, value in pairs:
        lines.append(f"      {key}: {yaml_scalar(value)}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", required=True, help="path to a resolve_result.*.json")
    parser.add_argument("--service", required=True, help="compose service name to configure")
    parser.add_argument("--out", default="", help="output path (default: stdout)")
    args = parser.parse_args(argv)

    try:
        with open(args.snapshot, "r", encoding="utf-8") as handle:
            snapshot = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"ERROR: cannot read snapshot {args.snapshot!r}: {exc}", file=sys.stderr)
        return 1

    if snapshot.get("status") != "ok":
        print(
            f"ERROR: refusing to generate from a non-ok snapshot (status="
            f"{snapshot.get('status')!r})",
            file=sys.stderr,
        )
        return 1
    if not snapshot.get("resolve_hash"):
        print("ERROR: snapshot carries no resolve_hash; refusing to generate", file=sys.stderr)
        return 1

    rendered = render_override(snapshot, args.service)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as out:
            out.write(rendered)
        print(f"wrote compose override for service '{args.service}' -> {args.out}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
