// SPDX-License-Identifier: BUSL-1.1

pub fn export_resolved(request: ExportResolvedRequest) -> ExportResolvedResult {
    let model_hash = request.resolve_result.model_hash.clone();
    let scope = request.resolve_result.scope.clone();
    let profile = request.profile.clone();

    if request.schema_version != PRODUCT_SCHEMA_VERSION {
        return export_resolved_failed(
            model_hash,
            scope,
            None,
            vec![Diagnostic {
                code: E_LOADER_UNSUPPORTED_SCHEMA_VERSION.to_string(),
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "Unsupported schema_version {} (expected {})",
                    request.schema_version, PRODUCT_SCHEMA_VERSION
                ),
                source_id: None,
                entity_path: None,
                hint: Some("Set request.schema_version to 1".to_string()),
            }],
        );
    }

    if request.profile != EXPORT_PROFILE_CPP_EARLY_BINDING_V1 {
        return export_resolved_failed(
            model_hash,
            scope,
            None,
            vec![Diagnostic {
                code: E_EXPORT_PROFILE_INVALID.to_string(),
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "Unsupported export profile '{}' (expected '{}')",
                    request.profile, EXPORT_PROFILE_CPP_EARLY_BINDING_V1
                ),
                source_id: None,
                entity_path: Some("export.profile".to_string()),
                hint: Some(
                    "Use profile 'cpp_early_binding_v1' for early-binding generation"
                        .to_string(),
                ),
            }],
        );
    }

    if request.resolve_result.schema_version != PRODUCT_SCHEMA_VERSION {
        return export_resolved_failed(
            model_hash,
            scope,
            None,
            vec![Diagnostic {
                code: E_EXPORT_RESOLVE_INVALID.to_string(),
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "resolve_result schema_version {} is unsupported (expected {})",
                    request.resolve_result.schema_version, PRODUCT_SCHEMA_VERSION
                ),
                source_id: None,
                entity_path: Some("resolve_result.schema_version".to_string()),
                hint: Some("Use resolve_result generated by resolve_from_selection".to_string()),
            }],
        );
    }

    if request.resolve_result.status != OperationStatus::Ok {
        return export_resolved_failed(
            model_hash,
            scope,
            request.resolve_result.resolve_hash.clone(),
            vec![Diagnostic {
                code: E_EXPORT_RESOLVE_INVALID.to_string(),
                severity: DiagnosticSeverity::Error,
                message: "resolve_result status is not 'ok'".to_string(),
                source_id: None,
                entity_path: Some("resolve_result.status".to_string()),
                hint: Some("Resolve successfully before calling export_resolved".to_string()),
            }],
        );
    }

    let resolve_hash = match request.resolve_result.resolve_hash {
        Some(hash) if !hash.trim().is_empty() => hash,
        _ => {
            return export_resolved_failed(
                model_hash,
                scope,
                None,
                vec![Diagnostic {
                    code: E_EXPORT_RESOLVE_INVALID.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: "resolve_result is missing resolve_hash".to_string(),
                    source_id: None,
                    entity_path: Some("resolve_result.resolve_hash".to_string()),
                    hint: Some("Resolve successfully before calling export_resolved".to_string()),
                }],
            )
        }
    };

    let resolved_output = match request.resolve_result.resolved_output {
        Some(value) => value,
        None => {
            return export_resolved_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                vec![Diagnostic {
                    code: E_EXPORT_RESOLVE_INVALID.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: "resolve_result is missing resolved_output".to_string(),
                    source_id: None,
                    entity_path: Some("resolve_result.resolved_output".to_string()),
                    hint: Some("Resolve successfully before calling export_resolved".to_string()),
                }],
            )
        }
    };

    let extraction = match extract_early_binding_payload(&resolved_output) {
        Ok(extraction) => extraction,
        Err(err) => {
            return export_resolved_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                vec![Diagnostic {
                    code: err.code.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: err.message,
                    source_id: None,
                    entity_path: err.entity_path,
                    hint: err.hint,
                }],
            );
        }
    };

    let header_contents = match emit_config_hpp(&extraction.construction_bindings) {
        Ok(contents) => contents,
        Err(err) => {
            return export_resolved_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                vec![Diagnostic {
                    code: err.code.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: err.message,
                    source_id: None,
                    entity_path: err.entity_path,
                    hint: err.hint,
                }],
            );
        }
    };

    let cmake_contents = match emit_config_build_flags(&extraction.construction_bindings) {
        Ok(contents) => contents,
        Err(err) => {
            return export_resolved_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                vec![Diagnostic {
                    code: err.code.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: err.message,
                    source_id: None,
                    entity_path: err.entity_path,
                    hint: err.hint,
                }],
            );
        }
    };

    let artifact_manifest_contents = match emit_config_artifact_manifest(
        &profile,
        &model_hash,
        &resolve_hash,
        &extraction.artifact_manifest_entries,
    ) {
        Ok(contents) => contents,
        Err(err) => {
            return export_resolved_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                vec![Diagnostic {
                    code: err.code.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: err.message,
                    source_id: None,
                    entity_path: err.entity_path,
                    hint: err.hint,
                }],
            );
        }
    };

    let mut files = vec![
        GeneratedArtifact {
            path: GENERATED_CONFIG_HPP_PATH.to_string(),
            content_hash: sha256_hex(header_contents.as_bytes()),
            contents: header_contents,
        },
        GeneratedArtifact {
            path: GENERATED_CONFIG_BUILD_FLAGS_PATH.to_string(),
            content_hash: sha256_hex(cmake_contents.as_bytes()),
            contents: cmake_contents,
        },
        GeneratedArtifact {
            path: GENERATED_CONFIG_ARTIFACT_MANIFEST_PATH.to_string(),
            content_hash: sha256_hex(artifact_manifest_contents.as_bytes()),
            contents: artifact_manifest_contents,
        },
    ];
    files.sort_by(|a, b| a.path.cmp(&b.path));

    let generator_hash =
        match compute_generator_hash(&profile, &model_hash, &scope, &resolve_hash, &files) {
            Ok(hash) => hash,
            Err(err) => {
                return export_resolved_failed(
                    model_hash,
                    scope,
                    Some(resolve_hash),
                    vec![Diagnostic {
                        code: E_EXPORT_FAILED.to_string(),
                        severity: DiagnosticSeverity::Error,
                        message: err.to_string(),
                        source_id: None,
                        entity_path: None,
                        hint: Some(
                            "Generated artifact payload must be canonically serializable"
                                .to_string(),
                        ),
                    }],
                );
            }
        };

    export_resolved_ok(
        model_hash,
        scope,
        Some(resolve_hash),
        GeneratedArtifacts {
            profile,
            generator_hash,
            files,
        },
    )
}

