// SPDX-License-Identifier: BUSL-1.1

pub fn export_software_bom(request: ExportSoftwareBomRequest) -> ExportSoftwareBomResult {
    let model_hash = request.resolve_result.model_hash.clone();
    let scope = request.resolve_result.scope.clone();
    let profile = request.profile.clone();

    if request.schema_version != PRODUCT_SCHEMA_VERSION {
        return export_software_bom_failed(
            model_hash,
            scope,
            None,
            None,
            vec![Diagnostic {
                code: E_LOADER_UNSUPPORTED_SCHEMA_VERSION.to_string(),
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "Unsupported schema_version {} (expected {})",
                    request.schema_version, PRODUCT_SCHEMA_VERSION
                ),
                source_id: None,
                entity_path: None,
                hint: Some("Set request.schema_version to 1".to_string()),
            }],
        );
    }

    if request.profile != EXPORT_SOFTWARE_BOM_PROFILE_FULL_AUDIT
        && request.profile != EXPORT_SOFTWARE_BOM_PROFILE_VALUE_REDACTED
    {
        return export_software_bom_failed(
            model_hash,
            scope,
            None,
            None,
            vec![Diagnostic {
                code: E_SBOM_PROFILE_INVALID.to_string(),
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "Unsupported software BOM profile '{}' (expected '{}' or '{}')",
                    request.profile,
                    EXPORT_SOFTWARE_BOM_PROFILE_FULL_AUDIT,
                    EXPORT_SOFTWARE_BOM_PROFILE_VALUE_REDACTED
                ),
                source_id: None,
                entity_path: Some("export.profile".to_string()),
                hint: Some(
                    "Use profile 'full_audit' or 'value_redacted' for BOM export"
                        .to_string(),
                ),
            }],
        );
    }

    let resolve_result = request.resolve_result;
    if resolve_result.schema_version != PRODUCT_SCHEMA_VERSION {
        return export_software_bom_failed(
            model_hash,
            scope,
            None,
            None,
            vec![Diagnostic {
                code: E_SBOM_RESOLVE_INVALID.to_string(),
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "resolve_result schema_version {} is unsupported (expected {})",
                    resolve_result.schema_version, PRODUCT_SCHEMA_VERSION
                ),
                source_id: None,
                entity_path: Some("resolve_result.schema_version".to_string()),
                hint: Some(
                    "Use resolve_result generated by resolve_from_selection".to_string(),
                ),
            }],
        );
    }

    if resolve_result.status != OperationStatus::Ok {
        return export_software_bom_failed(
            model_hash,
            scope,
            resolve_result.resolve_hash.clone(),
            None,
            vec![Diagnostic {
                code: E_SBOM_RESOLVE_INVALID.to_string(),
                severity: DiagnosticSeverity::Error,
                message: "resolve_result status is not 'ok'".to_string(),
                source_id: None,
                entity_path: Some("resolve_result.status".to_string()),
                hint: Some("Resolve successfully before calling export_software_bom".to_string()),
            }],
        );
    }

    let resolve_hash = match &resolve_result.resolve_hash {
        Some(hash) if !hash.trim().is_empty() => hash.clone(),
        _ => {
            return export_software_bom_failed(
                model_hash,
                scope,
                None,
                None,
                vec![Diagnostic {
                    code: E_SBOM_RESOLVE_INVALID.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: "resolve_result is missing resolve_hash".to_string(),
                    source_id: None,
                    entity_path: Some("resolve_result.resolve_hash".to_string()),
                    hint: Some(
                        "Resolve successfully before calling export_software_bom".to_string(),
                    ),
                }],
            )
        }
    };

    let resolved_output = match &resolve_result.resolved_output {
        Some(value) => value.clone(),
        None => {
            return export_software_bom_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                None,
                vec![Diagnostic {
                    code: E_SBOM_RESOLVE_INVALID.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: "resolve_result is missing resolved_output".to_string(),
                    source_id: None,
                    entity_path: Some("resolve_result.resolved_output".to_string()),
                    hint: Some(
                        "Resolve successfully before calling export_software_bom".to_string(),
                    ),
                }],
            )
        }
    };

    let mut software_bom =
        match build_software_bom_payload(&profile, &resolve_result, &resolve_hash, resolved_output)
        {
            Ok(bom) => bom,
            Err(err) => {
                return export_software_bom_failed(
                    model_hash,
                    scope,
                    Some(resolve_hash),
                    None,
                    vec![Diagnostic {
                        code: err.code.to_string(),
                        severity: DiagnosticSeverity::Error,
                        message: err.message,
                        source_id: None,
                        entity_path: err.entity_path,
                        hint: err.hint,
                    }],
                );
            }
        };

    let bom_hash = match compute_software_bom_hash(&software_bom) {
        Ok(hash) => hash,
        Err(err) => {
            return export_software_bom_failed(
                model_hash,
                scope,
                Some(resolve_hash),
                None,
                vec![Diagnostic {
                    code: E_SBOM_FAILED.to_string(),
                    severity: DiagnosticSeverity::Error,
                    message: err.to_string(),
                    source_id: None,
                    entity_path: Some("software_bom".to_string()),
                    hint: Some("Software BOM payload must be canonically serializable".to_string()),
                }],
            );
        }
    };
    software_bom.bom_hash = bom_hash.clone();

    if let Err(err) = validate_software_bom_payload(&software_bom) {
        return export_software_bom_failed(
            model_hash,
            scope,
            Some(resolve_hash),
            Some(bom_hash),
            vec![Diagnostic {
                code: err.code.to_string(),
                severity: DiagnosticSeverity::Error,
                message: err.message,
                source_id: None,
                entity_path: err.entity_path,
                hint: err.hint,
            }],
        );
    }

    export_software_bom_ok(
        model_hash,
        scope,
        Some(resolve_hash),
        software_bom.bom_hash.clone(),
        software_bom,
    )
}

