# Hermetic, version-pinned `cue` binary for the CUE authoring front-end.
#
# Completes ADR-0021 Decision 5: the stock `cue` evaluator is fetched
# hermetically and version-locked through Bazel (the same pattern the repo uses
# for other external CLI tools), instead of relying on whatever `cue` happens to
# be on $PATH. Since ADR-0027 (L2) CUE owns inheritance/merge, so the evaluator
# version is load-bearing for model semantics (`model_hash`); pinning it keeps
# the exported fixtures reproducible.
#
# Supply-chain provenance (v0.16.1, official upstream cue-lang/cue releases):
#
#   linux_amd64
#     sha256 = 5d644c1305a2b86504c8dcd2ec829cf5b4999efc2cf51ee375624e0455f774ae
#     Source: this is the repo-blessed pin already verified in CI
#             (.github/workflows/cue-schema.yml). Re-downloading the official
#             asset and hashing it reproduces this exact digest, proving the
#             fetch path below resolves to the same upstream artifact.
#
#   linux_arm64
#     sha256 = 3cc715a9e969f87b93c4fa34cfaef5388b93e96efa20b248e8ad6826abd25a83
#     Source: computed from the official upstream release asset
#             cue_v0.16.1_linux_arm64.tar.gz. cue-lang/cue does not publish a
#             standalone checksums manifest for v0.16.1 (only the per-platform
#             archives), so the authoritative digest is the hash of the official
#             asset itself. It was derived via the same fetch+sha256 path that
#             reproduced the CI-blessed linux_amd64 digest above, so it carries
#             the same provenance guarantee.
#
# The archive lays the `cue` binary at its root (alongside LICENSE/README/doc),
# so `build_file_content` simply re-exports it.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Single source of truth for the pinned version. Consumed by the build
# provenance surface (//tools:cue_version) and asserted by the toolchain test.
CUE_VERSION = "0.16.1"

_BASE_URL = "https://github.com/cue-lang/cue/releases/download/v{version}/cue_v{version}_{platform}.tar.gz"

# platform key -> sha256 of the official upstream archive for CUE_VERSION.
_CUE_ARCHIVES = {
    "linux_amd64": "5d644c1305a2b86504c8dcd2ec829cf5b4999efc2cf51ee375624e0455f774ae",
    "linux_arm64": "3cc715a9e969f87b93c4fa34cfaef5388b93e96efa20b248e8ad6826abd25a83",
}

_BUILD_FILE_CONTENT = """\
# Generated by //tools:cue_toolchain.bzl - exposes the pinned cue binary.
package(default_visibility = ["//visibility:public"])

exports_files(["cue"])

filegroup(
    name = "binary",
    srcs = ["cue"],
)
"""

def _cue_repos_impl(_module_ctx):
    for platform, sha256 in _CUE_ARCHIVES.items():
        http_archive(
            name = "cue_{}".format(platform),
            urls = [_BASE_URL.format(version = CUE_VERSION, platform = platform)],
            sha256 = sha256,
            build_file_content = _BUILD_FILE_CONTENT,
        )

# Module extension that materializes one hermetic repo per supported platform.
# Declared (not tagged) extension: it takes no tags and always registers the
# full pinned set, so MODULE.bazel only needs `use_repo`.
cue_repos = module_extension(
    implementation = _cue_repos_impl,
)
